-- F15: revisao editorial dos nomes e descricoes do cardapio do Iracema (ortografia, acentuacao, capitalizacao).
-- Ja aplicado em producao (49 itens). Nao reaplicar. Sem mudanca de preco, categoria, ordem ou foto.
update public.cardapio_itens i set nome=v.n, descricao=case when v.k='ca6b849c' then i.descricao else v.d end
from (values
('9986da25',$q$Carne de panela com pãozinho$q$,$q$Carne de panela servida com pãozinho para molhar. Serve 2 pessoas.$q$),
('43edb0a4',$q$Coxinha de moranga com rabada$q$,$q$Porção com 6 unidades de coxinha de moranga recheada com rabada.$q$),
('b79e2d13',$q$Dupla mineira$q$,$q$Linguiça calabresa e mandioca frita, acompanhadas de maionese americana. Serve 2 pessoas.$q$),
('8402b4c8',$q$Dupla vegana$q$,$q$Linguiça de cogumelos e polenta frita, acompanhadas de molho de goiabada picante. Serve 2 pessoas.$q$),
('5dff3d9b',$q$Fritas$q$,$q$Porção de batata frita. Serve 2 pessoas.$q$),
('d6850209',$q$Fritas com queijo$q$,$q$Porção de batata frita com queijo. Serve 2 pessoas.$q$),
('084bf06a',$q$Fritas com cheddar e bacon$q$,$q$Porção de batata frita com cheddar e bacon. Serve 2 pessoas.$q$),
('03689205',$q$Isca de tilápia com fritas$q$,$q$Iscas de tilápia com batata frita e molho tártaro. Serve 2 a 3 pessoas.$q$),
('e936da5a',$q$Lombo cremoso com catupiry$q$,$q$Cubos de lombo suíno (300 g) salteados em refogado bem temperado e finalizados com catupiry. Acompanha pãozinho francês à parte.$q$),
('d039e985',$q$Arroz com costelão$q$,$q$Arroz feito no caldo, servido com costela bovina e gema curada. Serve 2 pessoas.$q$),
('e2c4ab01',$q$Bife a cavalo$q$,$q$Contrafilé grelhado na manteiga, servido com ovo e arroz. Acompanha batata frita e salada de alface e tomate.$q$),
('bfa452d8',$q$Filé de tilápia empanado$q$,$q$Filé de tilápia empanado, servido com arroz com alho, batata frita e salada.$q$),
('96a61966',$q$Prato infantil$q$,$q$Arroz, feijão, batata sorriso, alface e tomate. Escolha a proteína: isca de filé mignon ou isca de tilápia empanada.$q$),
('d6ee5ea6',$q$Talharim$q$,$q$Talharim na manteiga com alho.$q$),
('f06d3fa0',$q$Salada Caesar$q$,$q$Salada tradicional com peito de frango e mix de alfaces, finalizada com croutons, molho Caesar da casa, parmesão e azeite extravirgem.$q$),
('0a2f449a',$q$Arroz$q$,$q$Porção de arroz.$q$),
('2a6053fb',$q$Feijão$q$,$q$Porção de feijão.$q$),
('1d13ad72',$q$Brownie com sorvete de creme$q$,$q$Brownie acompanhado de geleia de morango da casa e uma bola de sorvete de creme.$q$),
('b5ed3741',$q$Bananinha crocante Iracema$q$,$q$Bananinha crocante com doce de leite de Viçosa, sorvete de creme e os segredinhos da nossa cozinha.$q$),
('24865029',$q$Água mineral$q$,$q$Água mineral em garrafa.$q$),
('6f501646',$q$Água tônica$q$,$q$Água tônica em lata.$q$),
('61e4f6c2',$q$Refrigerante$q$,$q$Coca-Cola (normal ou zero), FYS (guaraná, limão-siciliano ou laranja-pera) e Guaraná Antarctica.$q$),
('c0c4a7b2',$q$Suco natural$q$,$q$Laranja, limão ou maracujá. 400 ml.$q$),
('7780d85d',$q$Red Bull$q$,$q$Tradicional, Sugarfree, Tropical ou Melancia.$q$),
('206a7311',$q$Amstel Lager 269 ml$q$,$q$Sem glúten.$q$),
('ac5da42e',$q$Longneck 350 ml$q$,$q$Heineken, Heineken Zero ou Eisenbahn (Weizenbier, Session IPA, Pale Ale ou IPA).$q$),
('75ff6df0',$q$Flor do Norte$q$,$q$Refrescante, frutado e temperado. Gin de jambu, manjericão, limão e xarope de açúcar.$q$),
('4e1e63d2',$q$Geraldim$q$,$q$Refrescante, cítrico e frutado. Gin de jambu, notas de limão-siciliano, licor Brasil e bitter.$q$),
('b9dbc513',$q$Quintal da Jabu$q$,$q$Adocicado e refrescante. Gin de jambu, geleia e espuma de jabuticaba, soda de baunilha e limão-siciliano.$q$),
('ebec5f5c',$q$Almandina 56$q$,$q$Vodca Absolut, suco de limão, suco de abacaxi, xarope de baunilha, espuma de limão e raspas de limão.$q$),
('8bacd8ee',$q$Caipirinha$q$,$q$Cachaça, açúcar e limão.$q$),
('16dcba8b',$q$Caipivodca Absolut$q$,$q$Vodca Absolut, limão e açúcar, no estilo da caipirinha.$q$),
('e5a67be7',$q$Caipivodca Orloff$q$,$q$Vodca Orloff, limão e açúcar, no estilo da caipirinha.$q$),
('f9dd26f0',$q$Gin e Tônica$q$,$q$Gin, água tônica e limão-siciliano.$q$),
('0ee65590',$q$Irish Dulce$q$,$q$Uísque Jameson, notas de doce de leite e ginger ale.$q$),
('d9f2acf7',$q$James Tea$q$,$q$Uísque Jameson, limão e chá de pêssego.$q$),
('7b92793e',$q$Jameson Mule$q$,$q$Uísque Jameson, ginger ale, espuma de gengibre e canela.$q$),
('cb559fd6',$q$Lábios de Mel$q$,$q$Gin, notas de rosa e St. Pierre Pink Lemonade.$q$),
('83adfe16',$q$Madame Rosell$q$,$q$Gin com infusão de hibisco, suco de limão e ginger ale.$q$),
('17dea940',$q$Moscow Mule$q$,$q$Vodca Absolut, suco de limão e espuma de gengibre.$q$),
('ac990157',$q$Porn Star$q$,$q$Vodca Absolut, xarope de baunilha, suco de maracujá e suco de limão.$q$),
('75b597b5',$q$Sensação de Morango$q$,$q$Vodca Orloff, morango, xarope de baunilha, leite condensado e chantilly.$q$),
('939417e3',$q$Tropical Gin$q$,$q$Gin com Red Bull Tropical.$q$),
('5429edaf',$q$Tropicana$q$,$q$Gin, maracujá, limão, soda de grapefruit, espuma de limão e raspas de limão.$q$),
('c0d4b961',$q$Xeque-Mate$q$,$q$Chá mate (300 ml) com rodelas de limão e gelo.$q$),
('641eff0f',$q$Soda italiana$q$,$q$Xarope de fruta, água gasosa, limão e gelo. Sabores: tangerina ou lichia.$q$),
('ab5bad47',$q$Delícias de Verão$q$,$q$Xarope de baunilha, água gasosa, leite condensado, chantilly e gelo. Sabores: morango, limão ou maracujá.$q$),
('ca6b849c',$q$Dose de uísque Jack Daniel's$q$,NULL),
('7b6635e0',$q$Harumaki de carne de panela$q$,$q$Cinco harumakis de carne de panela, servidos com molho picante de cebola caramelizada.$q$)
) as v(k,n,d)
where left(i.id::text,8)=v.k and i.tenant_id='13bb5e82-5d83-4db6-9fdc-aa0653bc83cc'::uuid
returning v.k;