/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterIndexRouteImport } from './routes/master.index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as MasterLoginRouteImport } from './routes/master.login'
import { Route as SlugObrigadoRouteImport } from './routes/$slug.obrigado'
import { Route as SlugAcompanharRouteImport } from './routes/$slug.acompanhar'
import { Route as SlugAdminIndexRouteImport } from './routes/$slug.admin.index'
import { Route as SlugReservarTipoRouteImport } from './routes/$slug.reservar.$tipo'
import { Route as SlugAdminLoginRouteImport } from './routes/$slug.admin.login'
import { Route as SlugAcompanharCodigoRouteImport } from './routes/$slug.acompanhar.$codigo'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/master/',
  path: '/master/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterLoginRoute = MasterLoginRouteImport.update({
  id: '/master/login',
  path: '/master/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugObrigadoRoute = SlugObrigadoRouteImport.update({
  id: '/$slug/obrigado',
  path: '/$slug/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugAcompanharRoute = SlugAcompanharRouteImport.update({
  id: '/$slug/acompanhar',
  path: '/$slug/acompanhar',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugAdminIndexRoute = SlugAdminIndexRouteImport.update({
  id: '/$slug/admin/',
  path: '/$slug/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugReservarTipoRoute = SlugReservarTipoRouteImport.update({
  id: '/$slug/reservar/$tipo',
  path: '/$slug/reservar/$tipo',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugAdminLoginRoute = SlugAdminLoginRouteImport.update({
  id: '/$slug/admin/login',
  path: '/$slug/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugAcompanharCodigoRoute = SlugAcompanharCodigoRouteImport.update({
  id: '/$codigo',
  path: '/$codigo',
  getParentRoute: () => SlugAcompanharRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$slug/acompanhar': typeof SlugAcompanharRouteWithChildren
  '/$slug/obrigado': typeof SlugObrigadoRoute
  '/master/login': typeof MasterLoginRoute
  '/$slug/': typeof SlugIndexRoute
  '/master/': typeof MasterIndexRoute
  '/$slug/acompanhar/$codigo': typeof SlugAcompanharCodigoRoute
  '/$slug/admin/login': typeof SlugAdminLoginRoute
  '/$slug/reservar/$tipo': typeof SlugReservarTipoRoute
  '/$slug/admin/': typeof SlugAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$slug/acompanhar': typeof SlugAcompanharRouteWithChildren
  '/$slug/obrigado': typeof SlugObrigadoRoute
  '/master/login': typeof MasterLoginRoute
  '/$slug': typeof SlugIndexRoute
  '/master': typeof MasterIndexRoute
  '/$slug/acompanhar/$codigo': typeof SlugAcompanharCodigoRoute
  '/$slug/admin/login': typeof SlugAdminLoginRoute
  '/$slug/reservar/$tipo': typeof SlugReservarTipoRoute
  '/$slug/admin': typeof SlugAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$slug/acompanhar': typeof SlugAcompanharRouteWithChildren
  '/$slug/obrigado': typeof SlugObrigadoRoute
  '/master/login': typeof MasterLoginRoute
  '/$slug/': typeof SlugIndexRoute
  '/master/': typeof MasterIndexRoute
  '/$slug/acompanhar/$codigo': typeof SlugAcompanharCodigoRoute
  '/$slug/admin/login': typeof SlugAdminLoginRoute
  '/$slug/reservar/$tipo': typeof SlugReservarTipoRoute
  '/$slug/admin/': typeof SlugAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/$slug/acompanhar'
    | '/$slug/obrigado'
    | '/master/login'
    | '/$slug/'
    | '/master/'
    | '/$slug/acompanhar/$codigo'
    | '/$slug/admin/login'
    | '/$slug/reservar/$tipo'
    | '/$slug/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$slug/acompanhar'
    | '/$slug/obrigado'
    | '/master/login'
    | '/$slug'
    | '/master'
    | '/$slug/acompanhar/$codigo'
    | '/$slug/admin/login'
    | '/$slug/reservar/$tipo'
    | '/$slug/admin'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/$slug/acompanhar'
    | '/$slug/obrigado'
    | '/master/login'
    | '/$slug/'
    | '/master/'
    | '/$slug/acompanhar/$codigo'
    | '/$slug/admin/login'
    | '/$slug/reservar/$tipo'
    | '/$slug/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlugAcompanharRoute: typeof SlugAcompanharRouteWithChildren
  SlugObrigadoRoute: typeof SlugObrigadoRoute
  MasterLoginRoute: typeof MasterLoginRoute
  SlugIndexRoute: typeof SlugIndexRoute
  MasterIndexRoute: typeof MasterIndexRoute
  SlugAdminLoginRoute: typeof SlugAdminLoginRoute
  SlugReservarTipoRoute: typeof SlugReservarTipoRoute
  SlugAdminIndexRoute: typeof SlugAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/master'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/login': {
      id: '/master/login'
      path: '/master/login'
      fullPath: '/master/login'
      preLoaderRoute: typeof MasterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/obrigado': {
      id: '/$slug/obrigado'
      path: '/$slug/obrigado'
      fullPath: '/$slug/obrigado'
      preLoaderRoute: typeof SlugObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/acompanhar': {
      id: '/$slug/acompanhar'
      path: '/$slug/acompanhar'
      fullPath: '/$slug/acompanhar'
      preLoaderRoute: typeof SlugAcompanharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/admin/': {
      id: '/$slug/admin/'
      path: '/$slug/admin'
      fullPath: '/$slug/admin/'
      preLoaderRoute: typeof SlugAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/reservar/$tipo': {
      id: '/$slug/reservar/$tipo'
      path: '/$slug/reservar/$tipo'
      fullPath: '/$slug/reservar/$tipo'
      preLoaderRoute: typeof SlugReservarTipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/admin/login': {
      id: '/$slug/admin/login'
      path: '/$slug/admin/login'
      fullPath: '/$slug/admin/login'
      preLoaderRoute: typeof SlugAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/acompanhar/$codigo': {
      id: '/$slug/acompanhar/$codigo'
      path: '/$codigo'
      fullPath: '/$slug/acompanhar/$codigo'
      preLoaderRoute: typeof SlugAcompanharCodigoRouteImport
      parentRoute: typeof SlugAcompanharRoute
    }
  }
}

interface SlugAcompanharRouteChildren {
  SlugAcompanharCodigoRoute: typeof SlugAcompanharCodigoRoute
}

const SlugAcompanharRouteChildren: SlugAcompanharRouteChildren = {
  SlugAcompanharCodigoRoute: SlugAcompanharCodigoRoute,
}

const SlugAcompanharRouteWithChildren = SlugAcompanharRoute._addFileChildren(
  SlugAcompanharRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlugAcompanharRoute: SlugAcompanharRouteWithChildren,
  SlugObrigadoRoute: SlugObrigadoRoute,
  MasterLoginRoute: MasterLoginRoute,
  SlugIndexRoute: SlugIndexRoute,
  MasterIndexRoute: MasterIndexRoute,
  SlugAdminLoginRoute: SlugAdminLoginRoute,
  SlugReservarTipoRoute: SlugReservarTipoRoute,
  SlugAdminIndexRoute: SlugAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
